### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lucamontana** [abhi-6988/YouTube-videos#1]
I get the following error when I run the 1. DetOfCompMatrices.py file:

Traceback (most recent call last):
  File "/home/luca/man/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/home/luca/man/manim/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "1. DetOfCompMatrices.py", line 226, in construct
    back_grid,fore_grid = self.background_plane,self.plane
AttributeError: 'AnyAreaScalesBySameFactor' object has no attribute 'plane'

Any suggestion how to overcome it?

Bests
LUCA

**Comment by abhi-6988** [comment]
@lucamontana 
I've modified the source code here and there a bit according to my workflow. The error is because of the keyword `"include_foreground_plane"` in the CONFIG dict, being set to false. 

Take the line 332 (`self.plane = NumberPlane(**self.foreground_plane_kwargs)`) in the file **vector_space_scene.py**  out of the **if** condition and that should work.

**Comment by lucamontana** [comment]
I did exactly what you said, however it didn't work. I still get the same error no matter if I comment the line 332 of vector_space_scene.py in manim or not!

**Comment by abhi-6988** [comment]
@lucamontana  Sorry if my instructions weren't clear, I meant place that line of code above the **if** condition as shown here.
![Screenshot (222)](https://user-images.githubusercontent.com/64465542/82138207-4cabab00-983c-11ea-9b43-0d165a2a3fef.png)

**Comment by lucamontana** [comment]
Thanks a  a lot. It works now, however when I try to run the 3.LeibnitzRule_p2.py file, I get 
[mob.scale_in_place(0.8) for mob in t_num_line.numbers]
AttributeError: 'NumberLine' object has no attribute 'numbers'

It seems that something is missing in the code. What should be done here?

**Comment by lucamontana** [comment]
In another part of the code, I get this error: 
File "LEIBNITZ_01.py", line 508, in <listcomp>
self.play(*[FadeOut(mob) for mob in [*self.mobjects] if mob is not self.board],lag_ratio=0.15)
AttributeError: 'PrevVid' object has no attribute 'board'

**Comment by abhi-6988** [comment]
> Thanks a a lot. It works now, however when I try to run the 3.LeibnitzRule_p2.py file, I get
> [mob.scale_in_place(0.8) for mob in t_num_line.numbers]
> AttributeError: 'NumberLine' object has no attribute 'numbers'
> 
> It seems that something is missing in the code. What should be done here?

@lucamontana  Sorry, I haven't checked your question...In line 57 of the same file, add the key-value pair `"include_numbers" : True`  in the dict `t_num_line_kwargs` and that should work.

**Comment by abhi-6988** [comment]
> In another part of the code, I get this error:
> File "LEIBNITZ_01.py", line 508, in
> self.play(*[FadeOut(mob) for mob in [*self.mobjects] if mob is not self.board],lag_ratio=0.15)
> AttributeError: 'PrevVid' object has no attribute 'board'
@lucamontana 
I don't see what's wrong here, it's working for me.

**Comment by AtomSeven** [comment]
Hi,

I'm having the following error:

![image](https://user-images.githubusercontent.com/30257875/85954993-7a276080-b973-11ea-8eff-dc756c31d52a.png)

**Comment by abhi-6988** [comment]
@AtomSeven  Use `self.setup_axes(animate=True)` in line 74 and comment out the line 83, that should work.
